name: Auto-sync forks
on:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC; adjust as needed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Run sync script
        env:
          FORKS_MANAGER_PAT: ${{ secrets.FORKS_MANAGER_PAT }}
        run: |
          chmod +x scripts/sync_forks.py
          python scripts/sync_forks.py